# Generated by Django 4.0.5 on 2022-07-11 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_register',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=50, null=True)),
                ('StudentClass', models.CharField(max_length=10, null=True)),
                ('StudentAge', models.PositiveIntegerField()),
                ('StudentGender', models.CharField(max_length=6, null=True)),
                ('StudentJoiningDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_register',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=50, null=True)),
                ('TeacherClass', models.CharField(max_length=10, null=True)),
                ('TeacherJoiningDate', models.DateTimeField(auto_now_add=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('idattendance', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=10, null=True)),
                ('StudentClass', models.CharField(max_length=10, null=True)),
                ('StudentAttendance', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_teacher.student_register')),
            ],
        ),
    ]
